### ISSUE TITLE
AWS AppSync

### ISSUE THREAD

**Issue by huyuplift** [monojack/graphql-normalizr#23]
Any chance this would support AWS AppSync/Amplify and the files it generates: `schema.json` ?

**Comment by monojack** [comment]
@huyuplift, I'm not sure I understand what you're asking, but you don't need a schema to use graphql-normalizr. The only requirement is for the `__typename` fields to be present on the response data.

**Comment by huyuplift** [comment]
Ah ok, I just have to figure out how to make AWS Amplify return that `__typename`.

**Comment by monojack** [comment]
> Ah ok, I just have to figure out how to make AWS Amplify return that `__typename`.

I guess you just have to ask for it? Add the field in your query and it should be part of the response. I haven't used Amplify yet but I guess you still create the queries yourself, right? There's no weird abstraction for that, is it?
