### ISSUE TITLE
Normalizing types without id

### ISSUE THREAD

**Issue by frankPairs** [monojack/graphql-normalizr#24]
Hi contributors!

First at all, congrats for the library I find it very useful and I think you are doing a good job.

My issue is about types without id's. My example is simple: I have one type CurrencyModel and it look like this.

```
type CurrencyModel {
   value: String!
   currency: String!
}
```
As you can se, this type doesn't have any identifier property. Now we have another type called Product, and some properties are:

```
type Product {
  id: ID!
  name: String!
  price: CurrencyModel
}
```
With this case, and after using the library,  the object is like:

```
{
  Products: [{ id: 1, name: 'Product', price: undefined }],
  CurrencyModel: [{ value: 1000, currency: 'US' }]
}
```

So I would like to avoid normalize the CurrencyModel type. Is there any way to do it?

Thanks in advance.

**Comment by monojack** [comment]
Hi, @frankPairs, normally I would suggest you assign ids to everything, but I agree that in some cases it may not be relevant enough. Preventing normalization in this case seems like a good idea and I'll look into it asap.

**Comment by frankPairs** [comment]
@monojack thanks for replying so fast!
