### ISSUE TITLE
Throws on empty array

### ISSUE THREAD

**Issue by futpib** [monojack/graphql-normalizr#25]
:heavy_check_mark:
```js
(new require('graphql-normalizr').GraphQLNormalizr()).normalize({
  data: { query: [ { id: 1, __typename: 'Foo' } ] },
});

→ { foos: { '1': { id: 1 } } }
```

:x:
```js
(new require('graphql-normalizr').GraphQLNormalizr()).normalize({
  data: { query: [] },
});

Error: [GraphQLNormalizr]: No "__typename" field found on node {}
    at assoc (.../node_modules/graphql-normalizr/lib/graphql-normalizr.cjs.js:530:30)
    at walk (.../node_modules/graphql-normalizr/lib/graphql-normalizr.cjs.js:586:13)
    at Object.normalize (.../node_modules/graphql-normalizr/lib/graphql-normalizr.cjs.js:593:7)

```

Instead expected output like this (omitted key for typename `Foo`):
```js
→ {}
```

**Comment by monojack** [comment]
thanks! will check it asap!

**Comment by monojack** [comment]
@futpib, I think the output should be `{  foos: []  }`, do you have a good reason for it being `{}`?

**Comment by futpib** [comment]
@monojack Sorry, I messed up the example and just edited it.

The reason it can't be `foos` is that a response like `data: { query: [] }` does not contain any `__typename: 'Foo'` to derive `foos` from.

**Comment by monojack** [comment]
But `query` does have a type, it's `[Something]`, though you can't read it from a `__typename`. I think the correct approach is to output `{ foos: [] }` since it reflects the type definition which allows an empty array. Hmm..

**Comment by monojack** [comment]
So I went with your advise, I guess there's no point normalizing data that isn't there
