### ISSUE TITLE
Objects without id shouldn't need a __typename 

### ISSUE THREAD

**Issue by j2L4e** [monojack/graphql-normalizr#27]
Related to #24 

Objects that are excluded from normalization due to not having an ID, shouldn't need a __typename field.

We have metadata fields coming from Postgres JSONB columns that can be basically anything, so they come without IDs and `__typename`s. I'd expect them to remain untouched, yet `No "__typename" field found on node` is thrown.

**Comment by monojack** [comment]
Hi, @j2L4e. Sorry for getting back so late. I'm curious, though, how do you handle that type definition? Unless I'm missing something, you cannot have a field without a typename, even if that field is handled as `ANY` you should still have a custom type(scalar) for that.

**Comment by j2L4e** [comment]
No problem, thanks for taking the time.
Yes, the fields are `scalar JSON`. I use postgraphile (and, admittedly, don't know too much about the inner workings) to provide the GraphQL endpoint. The JSON scalar is generated here: https://github.com/graphile/graphile-engine/blob/master/packages/graphile-build-pg/src/GraphQLJSON.js

To me it seems like during normalization objects are expected to be inherently non-scalar (i.e. always `type`s) but in this case they'd actually need to be handled like a scalar.

**Comment by j2L4e** [comment]
In case you're into docker:

```
docker run --rm -p 5433:5432 --tmpfs /var/lib/postgresql/data --name mypg postgres:11-alpine
docker run --rm --network host graphile/postgraphile --connection postgres://postgres:postgres@localhost:5433/postgres --schema public --watch --enhance-graphiql --dynamic-json
docker exec -it mypg psql -U postgres

# insert:

create table my_table (
    id serial primary key,
    json_object jsonb not null default '{ "somefield": 7, "yetanotherone": { "prop1": 42, "prop2": 1337 } }'
);

insert into my_table default values;
insert into my_table default values;
insert into my_table default values;
insert into my_table default values;
```

goto http://localhost:5000/graphiql to reproduce

**Comment by michaelbridge** [comment]
Also encountering this issue with postgraphile.  Here is further discussion from the repo owner regarding custom scalars:

https://github.com/graphile/postgraphile/issues/688

**Comment by monojack** [comment]
Hello. I haven't been able to keep up with stuff lately, if anyone could help with this one I'd gladly review and merge a PR. Or I'll get to it when I have a little more time.

**Comment by j2L4e** [comment]
A more generic way might be to provide an list of fields that should be excluded from normalization (handled like a scalar):

```
exclude: {
  typeA: [ fieldA, fieldB ],
  typeB: [ fieldX ]
}
```
