### ISSUE TITLE
Problem with foreign key references that are null?

### ISSUE THREAD

**Issue by gizm0duck** [monojack/graphql-normalizr#3]
I am getting an error that appears to be related to trying to normalize a single related object. All of my "many" associations work fine though.

I have a query that looks like this:

`profile {
      id
      primaryAddress {
        id
        countryCode
      }
    }`

in this case the user does not have a primaryAddress on their profile so it is null. The error I am seeing is this:

`ERROR TypeError: Cannot read property '__typename' of null
    at visit (GraphQLNormalizr.js:148)
    at visit (GraphQLNormalizr.js:154)
    at visit (GraphQLNormalizr.js:154)
    at normalize (GraphQLNormalizr.js:162)
    at index.ts:54
    at step (reducer.ts:94)
    at Object.next (reducer.ts:94)
    at next (proc.js:311)
    at currCb (proc.js:388)`

Is this expected behavior? I feel like I must be missing something but can't find any examples where this case is handled in the docs though.

**Comment by monojack** [comment]
@gizm0duck, not the intended behaviour, will look into it asap! thanks!
