### ISSUE TITLE
[Doc] Wrong output on README for `exclude` config prop

### ISSUE THREAD

**Issue by ozanmuyes** [monojack/graphql-normalizr#38]
Hello, thanks for the repo!

While I was reading through the README when I get to the [`exclude` config prop](https://github.com/monojack/graphql-normalizr/blob/8b27d5c59755ad5ff816ad808703ec5bb5f969f2/README.md#exclude) section I realized the output of `normalize(response)` still has excluded fields (`preferences` for `users` and `tags` for `blogPosts`. Am I missing something or just the output is wrong?

Have a good one.

**Comment by monojack** [comment]
Hi, @ozanmuyes! Maybe `exclude` is not the correct term here, but the idea is not to remove the field completely, but to prevent normalization. Is that what you were expecting?
