### ISSUE TITLE
Build process fails with 'BABEL_ENV' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by ivan006** [monojack/graphql-normalizr#41]
I'm encountering an issue when trying to install `@blue-chip/core` which has a dependency on `graphql-normalizr`. The build process for `graphql-normalizr` fails with the error `'BABEL_ENV' is not recognized as an internal or external command`.

**Steps to Reproduce**:
1. Run `npm i -S @blue-chip/core` in my project directory.
2. Encounter the following error during the installation process:

   ```
   npm ERR! > graphql-normalizr@1.0.2 prepare
   npm ERR! > npm run clean && npm run build
   ...
   npm ERR! > graphql-normalizr@1.0.2 build:cjs
   npm ERR! > BABEL_ENV=cjs babel src --out-dir lib
   npm ERR! 'BABEL_ENV' is not recognized as an internal or external command,
   npm ERR! operable program or batch file.
   ```

**Expected Behavior**:
I expect the installation process to complete successfully without any errors.

**Environment**:
- OS: Windows 10
- Node.js version: 21.7.1
- `graphql-normalizr` version: 1.0.2

**Additional Context**:
I've tried setting the `BABEL_ENV` environment variable in the `package.json` file using `cross-env`, but the issue persists. Any assistance in resolving this would be greatly appreciated.

**Comment by monojack** [comment]
Hi, @ivan006. Looks like blue-chip are using their own [fork of graphql-normalizr](https://github.com/blue-chip-js/blue-chip/blob/bd00e7da07f3b3417d0934c910c651347fb60ea5/package.json#L25) which is probably why it's trying to build it because that shouldn't be the case normally
