### ISSUE TITLE
Array with ids doesn't seem to get created

### ISSUE THREAD

**Issue by sanjaypojo** [monojack/graphql-normalizr#7]
Hi @monojack, thanks for the library. I'm using the normalize function alone. Here's the input:
```json
{
  "data": {
    "apps": {
      "nodes": [
        {
          "id": 2,
          "title": "Foo",
          "active": true,
          "imageUrl": "http://google.com/foo",
          "modes": {
            "nodes": [
              {
                "id": 1,
                "title": "slow",
                "active": true,
                "numMatchPlayers": 2,
                "__typename": "Mode"
              }
            ],
            "__typename": "ModesConnection"
          },
          "__typename": "App"
        },
        {
          "id": 3,
          "title": "Bar",
          "active": true,
          "imageUrl": "http://google.com/bar",
          "modes": {
            "nodes": [
              {
                "id": 2,
                "title": "fast",
                "active": true,
                "numMatchPlayers": 2,
                "__typename": "Mode"
              }
            ],
            "__typename": "ModesConnection"
          },
          "__typename": "App"
        }
      ],
      "__typename": "AppsConnection"
    }
  },
  "loading": false,
  "networkStatus": 7,
  "stale": false
}

```

And here's the output after calling normalize.

```json
{
  "apps": {
    "2": {
      "id": 2,
      "title": "Foo",
      "active": true,
      "imageUrl": "http://google.com/foo"
    },
    "3": {
      "id": 3,
      "title": "Bar",
      "active": true,
      "imageUrl": "http://google.com/bar"
    }
  },
  "modes": {
    "1": {
      "id": 1,
      "title": "slow",
      "active": true,
      "numMatchPlayers": 2
    },
    "2": {
      "id": 2,
      "title": "fast",
      "active": true,
      "numMatchPlayers": 2
    }
  }
}
```
I expected each of the `apps` to contain a key called `modes` with an array of the ids. Is this a bug or do I need to do something differently?

Thanks for your help!

**Comment by monojack** [comment]
@sanjaypojo , hi! 
It doesn't support GraphQL connections yet. I'm working towards this but I can't estimate when it would be implemented.

For now, if you could strip the `nodes` from your data it should work. Of course, that is an extra step for you, but it shouldn't have a significant impact.

**Comment by monojack** [comment]
Although, @sanjaypojo, it doesn't seem you are using GraphQL connections according to the spec, so it still wouldn't work after I add support for them.

**Comment by sanjaypojo** [comment]
Thanks for the quick response! Will check about why my API response doesn't match the spec. It's automatically generated using [Postgraphile](https://github.com/graphile/postgraphile), so I assumed it would be according to the spec.

**Comment by monojack** [comment]
> Thanks for the quick response! Will check about why my API response doesn't match the spec. It's automatically generated using [Postgraphile](https://github.com/graphile/postgraphile), so I assumed it would be according to the spec.

Says [here](https://www.graphile.org/postgraphile/connections/) it's an "enhancement".
