### ISSUE TITLE
Error when normalizing null fields with edges and nodes

### ISSUE THREAD

**Issue by dematerializer** [monojack/graphql-normalizr#9]
When trying to normalize entries with edges and nodes (`{useConnections: true}`) that have relational fields that are null, I get the following error:  
`TypeError: Cannot read property 'hasOwnProperty' of null`
pointing to line https://github.com/monojack/graphql-normalizr/blob/71b7b05bbbc469129c4661f0fb199831bf508943/src/GraphQLNormalizr.js#L124

**Comment by monojack** [comment]
@dematerializer, thanks! I'm on it 🗡

**Comment by dematerializer** [comment]
Thank you for this quick fix!
